client:
    label: Client
    view:
        toolbarButtons: create|add
        list: $/ocs/collection/models/client/columns.yaml
        form: $/ocs/collection/models/client/fields.yaml
    manage:
        showSearch: true
        form: $/ocs/collection/models/client/fields.yaml

debt:
    label: Debts    
    deferredBinding: true
    view:
        list: $/ocs/collection/models/debt/columns.yaml
        toolbarPartial: relation_toolbar
        recordsPerPage: 10
    # manage:
    #     showSearch: true
    #     form: $/ocs/collection/models/debt/fields.yaml
    #     recordsPerPage: 10