client:
    label: Client
    view:
        toolbarButtons: create|add
        list: $/ocs/collection/models/client/columns.yaml
        form: $/ocs/collection/models/client/fields.yaml
    manage:
        showSearch: true
        form: $/ocs/collection/models/client/fields.yaml

debt:
    label: Debts    
    deferredBinding: true
    view:
        showSearch: true
        list: $/ocs/collection/models/collection/columns_debt.yaml
        toolbarButtons: addDebt|delete
        recordsPerPage: 10
    # manage:
    #     form: $/ocs/collection/models/collection/fields_debt.yaml
    #     recordsPerPage: 10