debtor:
    label: Debtor
    view:
        toolbarButtons: create|add
        list: $/ocs/collection/models/debtor/columns.yaml
        form: $/ocs/collection/models/debtor/fields.yaml
    manage:
        showSearch: true
        form: $/ocs/collection/models/debtor/fields.yaml

payments:
    label: Payment
    view:
        showSearch: true
        toolbarButtons: add_payment | delete
        list: $/ocs/collection/models/debt/columns_payment.yaml
    manage:
        form: ~/plugins/ocs/collection/models/debt/fields_payment.yaml